version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/repo

    steps:
      - checkout

      # Run PHPCS test
      - run:
          name: Run PHPCS test
          command: |
            vendor/bin/phpcs --standard=Magento2 ./Model ./Command

      # Persist test results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build
